### ISSUE TITLE
Spring color

### ISSUE THREAD

**Issue by vikiival** [vikiival/shop#13]
Currently app shows spring anime waifus 

<img width="1680" alt="Screenshot 2023-03-17 at 10 34 59" src="https://user-images.githubusercontent.com/22471030/225867531-1448f4d0-c44e-4abe-9e21-94855a1837b4.png">

I would like to have more springish banner.
What are the hex codes @exezbcz?

![FrV9D3mWAAEjEMn](https://user-images.githubusercontent.com/22471030/225867843-c5cc50eb-c6b3-4e2e-88b7-ea9ff390a957.jpeg)

**Comment by exezbcz** [comment]
hey hey.
619C4E - green 
F5F2DE - light green

**Comment by vikiival** [comment]
Thank you! 


![tumblr_n09vc27lmC1t15wswo1_400](https://user-images.githubusercontent.com/22471030/225871167-d89b6f6c-1647-4df6-bf07-054ae1b66924.gif)
