### ISSUE TITLE
Remove deno.lock and add it to gitignore

### ISSUE THREAD

**Issue by poppyseedDev** [vikiival/shop#14]
I am new with Deno, but when I try to run deno (I also added .env file) I get the following error:

Task start deno run -A --watch=static/,routes, dev.ts
Watcher Process started.
The manifest has been generated for 4 routes and 3 islands.
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/bn.js@5.2.1
  Lock file: /Users/aurora/Desktop/Aurora/uniquery/shop/deno.lock

**Comment by vikiival** [comment]
So looks like deleting deno.lock works
