### ISSUE TITLE
Change banner

### ISSUE THREAD

**Issue by vikiival** [vikiival/shop#3]
App currently look like this

<img width="1792" alt="Screenshot 2023-03-09 at 13 41 24" src="https://user-images.githubusercontent.com/22471030/224026174-ae635eca-33cd-4096-af35-8c55d83c981f.png">

Maybe it wold be nice to have it more like our shop.

If @exezbcz can help me to drop some visuals I would be super happy.

**Comment by exezbcz** [comment]
what size is that? I can make smthing

lol
